name: stargazer
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.4.1
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  equatable: ^2.0.5
  freezed_annotation: ^3.0.0
  json_annotation: ^4.7.0
  build_runner: ^2.4.7
  intl: ^0.20.2
  devtools_extensions: ^0.3.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  path_provider: ^2.1.1
  path: ^1.9.0
  camera: ^0.11.1
  cupertino_icons: ^1.0.2
  camera_android: ^0.10.10
  http: ^1.1.0
  animated_text_kit: ^4.2.2
  tflite_flutter: ^0.11.0
  image_picker: ^1.1.2
  image: ^4.5.3
  google_generative_ai: ^0.4.6
  chat_bubbles: ^1.7.0
  material_color_utilities: ^0.11.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.1.6
  cloud_firestore: ^5.6.5
  firebase_database: ^11.3.4
  flutter_svg: ^2.0.17
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.9.4
  freezed: ^3.0.3
  mockito: ^5.4.4
  flutter_lints: ^5.0.0
  firebase_auth_mocks: ^0.14.1
  google_sign_in_mocks: ^0.3.0

flutter:
  uses-material-design: true

  fonts:
    - family: SF Pro
      fonts:
        - asset: lib/assets/fonts/SF-Pro/SF-Pro-Display-Light.otf
          weight: 300
        - asset: lib/assets/fonts/SF-Pro/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: lib/assets/fonts/SF-Pro/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: lib/assets/fonts/SF-Pro/SF-Pro-Display-Semibold.otf
          weight: 600

  assets:
    - lib/assets/images/
    - lib/assets/
    - lib/assets/svgs/
    - lib/assets/model/
    - lib/assets/model.tflite
    - lib/assets/images/
    - lib/assets/images/logo/
    - .env
