// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuQsn03198BwZD-3iqjf2asa2uSLsNzAg',
    appId: '1:1050874946405:web:321e0a93b0751658c6f78c',
    messagingSenderId: '1050874946405',
    projectId: 'capstoneproject-d401d',
    authDomain: 'capstoneproject-d401d.firebaseapp.com',
    storageBucket: 'capstoneproject-d401d.firebasestorage.app',
    measurementId: 'G-05H32MR3CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5PlPNUq0TqoINwOMYDW3PkUnLE5p3WpU',
    appId: '1:1050874946405:android:8c150629cc524028c6f78c',
    messagingSenderId: '1050874946405',
    projectId: 'capstoneproject-d401d',
    storageBucket: 'capstoneproject-d401d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAevMd4cLwxkNADp-QlvSrY4R-fiCY7aAk',
    appId: '1:1050874946405:ios:ca6515a1b97598a9c6f78c',
    messagingSenderId: '1050874946405',
    projectId: 'capstoneproject-d401d',
    storageBucket: 'capstoneproject-d401d.firebasestorage.app',
    iosBundleId: 'com.example.stargazer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAevMd4cLwxkNADp-QlvSrY4R-fiCY7aAk',
    appId: '1:1050874946405:ios:ca6515a1b97598a9c6f78c',
    messagingSenderId: '1050874946405',
    projectId: 'capstoneproject-d401d',
    storageBucket: 'capstoneproject-d401d.firebasestorage.app',
    iosBundleId: 'com.example.stargazer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuQsn03198BwZD-3iqjf2asa2uSLsNzAg',
    appId: '1:1050874946405:web:fea2a07648dc7a52c6f78c',
    messagingSenderId: '1050874946405',
    projectId: 'capstoneproject-d401d',
    authDomain: 'capstoneproject-d401d.firebaseapp.com',
    storageBucket: 'capstoneproject-d401d.firebasestorage.app',
    measurementId: 'G-JE58Y6BYS9',
  );
}
